FROM firefox

RUN apt-get install -y python-software-properties 
RUN apt-get install -y software-properties-common

RUN sudo add-apt-repository ppa:mystic-mirage/pycharm && sudo apt-get update && sudo apt-get -y install pycharm

